/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package besiusahamekar;

import MasterData.MasterMaterial;
import MasterData.MasterKonsumen;
import MasterData.MasterSupplier;
import MasterData.MasterUser;
import Pembelian.MaterialMasuk;
import Pembelian.PesananPembelian;
import Pembelian.ReturPembelian;
import Pembelian.TransaksiPembelian;
import Penjualan.MaterialKeluar;
import Penjualan.PesananPenjualan;
import Penjualan.ReturPenjualan;
import Penjualan.TransaksiPenjualan;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import static besiusahamekar.koneksidb.PathReport;

/**
 *
 * @author Banuajie
 */
public class MenuUtama extends javax.swing.JFrame {
public DefaultTableModel tabModel;
Connection conn;
String notrans;


    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();  
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo.jpg")));
        this.setBounds(0,0,screen.width,screen.height); 
    }

    public void cetakdaftarkonsumen(){
         String reportSource;
        String reportDest;
        
        Map<String, Object> param = new HashMap<String, Object>();
        //param.put("tipeitem", jCtipeitem.getSelectedItem().toString());
        try {

            reportSource = PathReport + "LaporanDaftarPelanggan.jrxml";
            reportDest = PathReport + "LaporanDaftarPelanggan.html";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param, conn);

            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);

            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println("Koneksi Mysql Gagal" + e.getMessage());
        }
    }
    
    
        public void cetakdaftarsupplier(){
        String reportSource;
        String reportDest;
        
        Map<String, Object> param = new HashMap<String, Object>();
        //param.put("tipeitem", jCtipeitem.getSelectedItem().toString());
        try {

            reportSource = PathReport + "LaporanDaftarSupplier.jrxml";
            reportDest = PathReport + "LaporanDaftarSupplier.html";

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param, conn);

            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);

            JasperViewer.viewReport(jasperPrint, false);

        } catch (Exception e) {
            System.out.println("Koneksi Mysql Gagal" + e.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jIMenuUtama = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jBmasteritem = new javax.swing.JButton();
        jBmasteruser = new javax.swing.JButton();
        jBmastersupplier = new javax.swing.JButton();
        jBkonsumen = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBpesananpembelian = new javax.swing.JButton();
        jBtransaksipembelian = new javax.swing.JButton();
        jBreturpembelian = new javax.swing.JButton();
        jBitemmasuk = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jBpesananpenjualan = new javax.swing.JButton();
        jBreturpenjualan = new javax.swing.JButton();
        jBtransaksipenjualan = new javax.swing.JButton();
        jBitemkeluar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLlaporanmasterdata = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLlaptransaksibeli = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jLlaptransaksijual = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jLlaplainlain = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        juser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama Sistem");

        jIMenuUtama.setTitle("Tabel Menu Sistem");
        jIMenuUtama.setVisible(true);

        jBmasteritem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Box.png"))); // NOI18N
        jBmasteritem.setText("Master Material");
        jBmasteritem.setMaximumSize(new java.awt.Dimension(260, 65));
        jBmasteritem.setMinimumSize(new java.awt.Dimension(260, 65));
        jBmasteritem.setPreferredSize(new java.awt.Dimension(260, 65));
        jBmasteritem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmasteritemActionPerformed(evt);
            }
        });

        jBmasteruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/46.png"))); // NOI18N
        jBmasteruser.setText("Master User");
        jBmasteruser.setMaximumSize(new java.awt.Dimension(260, 65));
        jBmasteruser.setMinimumSize(new java.awt.Dimension(260, 65));
        jBmasteruser.setPreferredSize(new java.awt.Dimension(260, 65));
        jBmasteruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmasteruserActionPerformed(evt);
            }
        });

        jBmastersupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Contact.png"))); // NOI18N
        jBmastersupplier.setText("Master Supplier");
        jBmastersupplier.setMaximumSize(new java.awt.Dimension(260, 65));
        jBmastersupplier.setMinimumSize(new java.awt.Dimension(260, 65));
        jBmastersupplier.setPreferredSize(new java.awt.Dimension(260, 65));
        jBmastersupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmastersupplierActionPerformed(evt);
            }
        });

        jBkonsumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kdmconfig.png"))); // NOI18N
        jBkonsumen.setText("Master Konsumen");
        jBkonsumen.setMaximumSize(new java.awt.Dimension(260, 65));
        jBkonsumen.setMinimumSize(new java.awt.Dimension(260, 65));
        jBkonsumen.setPreferredSize(new java.awt.Dimension(260, 65));
        jBkonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBkonsumenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBmasteritem, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jBmastersupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBmasteruser, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jBkonsumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBmasteritem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBmasteruser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBmastersupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBkonsumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Master Data", jPanel2);

        jBpesananpembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kate.png"))); // NOI18N
        jBpesananpembelian.setText("Order Pembelian");
        jBpesananpembelian.setMaximumSize(new java.awt.Dimension(260, 65));
        jBpesananpembelian.setMinimumSize(new java.awt.Dimension(260, 65));
        jBpesananpembelian.setPreferredSize(new java.awt.Dimension(260, 65));
        jBpesananpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesananpembelianActionPerformed(evt);
            }
        });

        jBtransaksipembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kcalc.png"))); // NOI18N
        jBtransaksipembelian.setText("Transaksi Pembelian");
        jBtransaksipembelian.setMaximumSize(new java.awt.Dimension(260, 65));
        jBtransaksipembelian.setMinimumSize(new java.awt.Dimension(260, 65));
        jBtransaksipembelian.setPreferredSize(new java.awt.Dimension(260, 65));
        jBtransaksipembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtransaksipembelianActionPerformed(evt);
            }
        });

        jBreturpembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fasilitas1.png"))); // NOI18N
        jBreturpembelian.setText("Retur Pembelian");
        jBreturpembelian.setMaximumSize(new java.awt.Dimension(260, 65));
        jBreturpembelian.setMinimumSize(new java.awt.Dimension(260, 65));
        jBreturpembelian.setPreferredSize(new java.awt.Dimension(260, 65));
        jBreturpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreturpembelianActionPerformed(evt);
            }
        });

        jBitemmasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Down.png"))); // NOI18N
        jBitemmasuk.setText("Material Masuk");
        jBitemmasuk.setMaximumSize(new java.awt.Dimension(260, 65));
        jBitemmasuk.setMinimumSize(new java.awt.Dimension(260, 65));
        jBitemmasuk.setPreferredSize(new java.awt.Dimension(260, 65));
        jBitemmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBitemmasukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBpesananpembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jBreturpembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtransaksipembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jBitemmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBpesananpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtransaksipembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBreturpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBitemmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaksi Pembelian", jPanel3);

        jBpesananpenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mail_Read.png"))); // NOI18N
        jBpesananpenjualan.setText("Order Penjualan");
        jBpesananpenjualan.setMaximumSize(new java.awt.Dimension(260, 65));
        jBpesananpenjualan.setMinimumSize(new java.awt.Dimension(260, 65));
        jBpesananpenjualan.setPreferredSize(new java.awt.Dimension(260, 65));
        jBpesananpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesananpenjualanActionPerformed(evt);
            }
        });

        jBreturpenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Template.png"))); // NOI18N
        jBreturpenjualan.setText("Retur Penjualan");
        jBreturpenjualan.setMaximumSize(new java.awt.Dimension(260, 65));
        jBreturpenjualan.setMinimumSize(new java.awt.Dimension(260, 65));
        jBreturpenjualan.setPreferredSize(new java.awt.Dimension(260, 65));
        jBreturpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreturpenjualanActionPerformed(evt);
            }
        });

        jBtransaksipenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gajian.png"))); // NOI18N
        jBtransaksipenjualan.setText("Transaksi Penjualan");
        jBtransaksipenjualan.setMaximumSize(new java.awt.Dimension(260, 65));
        jBtransaksipenjualan.setMinimumSize(new java.awt.Dimension(260, 65));
        jBtransaksipenjualan.setPreferredSize(new java.awt.Dimension(260, 65));
        jBtransaksipenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtransaksipenjualanActionPerformed(evt);
            }
        });

        jBitemkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Up.png"))); // NOI18N
        jBitemkeluar.setText("Material Keluar");
        jBitemkeluar.setMaximumSize(new java.awt.Dimension(260, 65));
        jBitemkeluar.setMinimumSize(new java.awt.Dimension(260, 65));
        jBitemkeluar.setPreferredSize(new java.awt.Dimension(260, 65));
        jBitemkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBitemkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBpesananpenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jBreturpenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtransaksipenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jBitemkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBpesananpenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtransaksipenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBreturpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBitemkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaksi Penjualan", jPanel4);

        jLlaporanmasterdata.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Laporan Daftar Material" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jLlaporanmasterdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLlaporanmasterdataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jLlaporanmasterdata);

        jScrollPane1.setViewportView(jScrollPane2);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Laporan Master Data");

        jLlaptransaksibeli.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Laporan Transaksi Pesanan", "Laporan Transaksi Pembelian", "Laporan Transaksi Retur" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jLlaptransaksibeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLlaptransaksibeliMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jLlaptransaksibeli);

        jScrollPane3.setViewportView(jScrollPane4);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Laporan Pembelian");

        jLlaptransaksijual.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Laporan Transaksi Pesanan", "Laporan Transaksi Penjualan", "Laporan Transaksi Retur" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jLlaptransaksijual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLlaptransaksijualMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jLlaptransaksijual);

        jScrollPane5.setViewportView(jScrollPane6);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Laporan Penjualan");

        jLlaplainlain.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Laporan Stok Material", "Laporan Material Dgn Id" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jLlaplainlain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLlaplainlainMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jLlaplainlain);

        jScrollPane7.setViewportView(jScrollPane8);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Laporan Stok Material");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menu Laporan", jPanel5);

        jLabel1.setText("Anda Terdaftar Sebagai :");

        juser.setEnabled(false);
        juser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserActionPerformed(evt);
            }
        });
        juser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                juserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                juserKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jIMenuUtamaLayout = new javax.swing.GroupLayout(jIMenuUtama.getContentPane());
        jIMenuUtama.getContentPane().setLayout(jIMenuUtamaLayout);
        jIMenuUtamaLayout.setHorizontalGroup(
            jIMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jIMenuUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(juser, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jIMenuUtamaLayout.setVerticalGroup(
            jIMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIMenuUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(juser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background_besiusahamekar.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        jDesktopPane.setLayer(jIMenuUtama, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jIMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1582, Short.MAX_VALUE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jIMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(776, Short.MAX_VALUE))
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
        LoginMenu lm = new LoginMenu();
        lm.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jBtransaksipenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtransaksipenjualanActionPerformed
        // TODO add your handling code here:
        TransaksiPenjualan di = new TransaksiPenjualan();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        String user = juser.getText();
        di.jTuser.setText(user);
        di.setVisible(true);
    }//GEN-LAST:event_jBtransaksipenjualanActionPerformed

    private void jBmastersupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmastersupplierActionPerformed
        // TODO add your handling code here:
        MasterSupplier di = new MasterSupplier();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        di.setVisible(true);
    }//GEN-LAST:event_jBmastersupplierActionPerformed

    private void juserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juserActionPerformed

    private void jBmasteritemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmasteritemActionPerformed
        // TODO add your handling code here:
        MasterMaterial di = new MasterMaterial();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        di.setVisible(true);
    }//GEN-LAST:event_jBmasteritemActionPerformed

    private void jBmasteruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmasteruserActionPerformed
        // TODO add your handling code here:
        MasterUser di = new MasterUser();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        di.setVisible(true);
    }//GEN-LAST:event_jBmasteruserActionPerformed

    private void jBkonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBkonsumenActionPerformed
        // TODO add your handling code here:
        MasterKonsumen di = new MasterKonsumen();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        di.setVisible(true);
    }//GEN-LAST:event_jBkonsumenActionPerformed

    private void jBpesananpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesananpembelianActionPerformed
        // TODO add your handling code here:
        PesananPembelian pp = new PesananPembelian();
        jDesktopPane.add(pp);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = pp.getSize();

        //set center screen
        pp.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //pp.moveToFront();
        String user = juser.getText();
        pp.jTuser.setText(user);
        pp.setVisible(true);
    }//GEN-LAST:event_jBpesananpembelianActionPerformed

    private void jBtransaksipembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtransaksipembelianActionPerformed
        // TODO add your handling code here:
        TransaksiPembelian di = new TransaksiPembelian();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        String user = juser.getText();
        di.jTuser.setText(user);
        di.setVisible(true);
    }//GEN-LAST:event_jBtransaksipembelianActionPerformed

    private void jBreturpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreturpembelianActionPerformed
        // TODO add your handling code here:
        ReturPembelian di = new ReturPembelian();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        String user = juser.getText();
        di.jTuser.setText(user);
        di.setVisible(true);
    }//GEN-LAST:event_jBreturpembelianActionPerformed

    private void jBitemmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBitemmasukActionPerformed
        // TODO add your handling code here:
        MaterialMasuk di = new MaterialMasuk();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        String user = juser.getText();
        di.jTuser.setText(user);
        di.setVisible(true);
    }//GEN-LAST:event_jBitemmasukActionPerformed

    private void jBpesananpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesananpenjualanActionPerformed
        // TODO add your handling code here:
        PesananPenjualan di = new PesananPenjualan();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        String user = juser.getText();
        di.jTuser.setText(user);
        di.setVisible(true);
    }//GEN-LAST:event_jBpesananpenjualanActionPerformed

    private void jBreturpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreturpenjualanActionPerformed
        // TODO add your handling code here:
        ReturPenjualan di = new ReturPenjualan();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        String user = juser.getText();
        di.jTuser.setText(user);
        di.setVisible(true);
    }//GEN-LAST:event_jBreturpenjualanActionPerformed

    private void jBitemkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBitemkeluarActionPerformed
        // TODO add your handling code here:
        MaterialKeluar di = new MaterialKeluar();
        jDesktopPane.add(di);
        Dimension parentSize = jDesktopPane.getSize();
        Dimension childSize = di.getSize();

        //set center screen
        di.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        //di.moveToFront();
        String user = juser.getText();
        di.jTuser.setText(user);
        di.setVisible(true);
    }//GEN-LAST:event_jBitemkeluarActionPerformed

    private void jLlaptransaksibeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLlaptransaksibeliMouseClicked
        // TODO add your handling code here:
        CetakBerdasarkan cb = new CetakBerdasarkan();
        jDesktopPane.add(cb);
        if (evt.getClickCount() == 2) {

            String pilihlist = jLlaptransaksibeli.getSelectedValue().toString();
            
            
            if(pilihlist.equals("Laporan Transaksi Pesanan")){
                cb.jDdari.setEnabled(true);
                cb.jDsampai.setEnabled(true);
                cb.jBsimpan.setEnabled(true);
                cb.jBsimpan.setText("Cetak Lap Beli");
                Dimension parentSize = jDesktopPane.getSize();
                Dimension childSize = cb.getSize();

                //set center screen
                cb.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
                //cb.moveToFront();
                cb.setVisible(true);

            }else if(pilihlist.equals("Laporan Transaksi Pembelian")){
                cb.jDdari.setEnabled(true);
                cb.jDsampai.setEnabled(true);
                cb.jBsimpan.setEnabled(true);
                cb.jCtipelap.setEnabled(true);
                cb.jBsimpan.setText("Cetak Lap Trans");
                Dimension parentSize = jDesktopPane.getSize();
                Dimension childSize = cb.getSize();

                //set center screen
                cb.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
                //cb.moveToFront();
                cb.setVisible(true);

            }else if(pilihlist.equals("Laporan Transaksi Retur")){
                cb.jDdari.setEnabled(true);
                cb.jDsampai.setEnabled(true);
                cb.jBsimpan.setEnabled(true);
                cb.jCtipelap.setEnabled(true);
                cb.jBsimpan.setText("Cetak Lap Retur");
                Dimension parentSize = jDesktopPane.getSize();
                Dimension childSize = cb.getSize();

                //set center screen
                cb.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
                //cb.moveToFront();
                cb.setVisible(true);
            }
        }
    }//GEN-LAST:event_jLlaptransaksibeliMouseClicked

    private void jLlaptransaksijualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLlaptransaksijualMouseClicked
        // TODO add your handling code here:
        CetakBerdasarkan cb = new CetakBerdasarkan();
        jDesktopPane.add(cb);
        if (evt.getClickCount() == 2) {

            String pilihlist = jLlaptransaksijual.getSelectedValue().toString();
            
            
            if(pilihlist.equals("Laporan Transaksi Pesanan")){
                cb.jDdari.setEnabled(true);
                cb.jDsampai.setEnabled(true);
                cb.jBsimpan.setEnabled(true);
                cb.jBsimpan.setText("Cetak Lap Jual");
                Dimension parentSize = jDesktopPane.getSize();
                Dimension childSize = cb.getSize();

                //set center screen
                cb.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
                //cb.moveToFront();
                cb.setVisible(true);

            }else if(pilihlist.equals("Laporan Transaksi Penjualan")){
                cb.jDdari.setEnabled(true);
                cb.jDsampai.setEnabled(true);
                cb.jBsimpan.setEnabled(true);
                cb.jCtipelap.setEnabled(true);
                cb.jBsimpan.setText("Cetak Lap Transs");
                Dimension parentSize = jDesktopPane.getSize();
                Dimension childSize = cb.getSize();

                //set center screen
                cb.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
                //cb.moveToFront();
                cb.setVisible(true);

            }else if(pilihlist.equals("Laporan Transaksi Retur")){
                cb.jDdari.setEnabled(true);
                cb.jDsampai.setEnabled(true);
                cb.jBsimpan.setEnabled(true);
                cb.jCtipelap.setEnabled(true);
                cb.jBsimpan.setText("Cetak Lap Returs");
                Dimension parentSize = jDesktopPane.getSize();
                Dimension childSize = cb.getSize();

                //set center screen
                cb.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
                //cb.moveToFront();
                cb.setVisible(true);
            }
        }
    }//GEN-LAST:event_jLlaptransaksijualMouseClicked

    private void jLlaplainlainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLlaplainlainMouseClicked
        // TODO add your handling code here:
        CetakBerdasarkan cb = new CetakBerdasarkan();
        jDesktopPane.add(cb);
        String pilihlist = jLlaplainlain.getSelectedValue().toString();
        
        
        if (evt.getClickCount() == 2) {
            if(pilihlist.equals("Laporan Stok Material")){
                cb.jDdari.setEnabled(true);
                cb.jDsampai.setEnabled(true);
                cb.jBsimpan.setEnabled(true);
                cb.jBsimpan.setText("Cetak Lap Stok");
                Dimension parentSize = jDesktopPane.getSize();
                Dimension childSize = cb.getSize();

                //set center screen
                cb.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
                //cb.moveToFront();
                cb.setVisible(true);

            }else if(pilihlist.equals("Laporan Material Dgn Id")){

                cb.jTkode.setEnabled(true);
                cb.jBsimpan.setEnabled(true);
                cb.jBsimpan.setText("Cetak Lap Stoks");
                Dimension parentSize = jDesktopPane.getSize();
                Dimension childSize = cb.getSize();

                //set center screen
                cb.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
                //cb.moveToFront();
                cb.setVisible(true);

            }
        }
    }//GEN-LAST:event_jLlaplainlainMouseClicked

    private void juserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_juserKeyTyped
        // TODO add your handling code here:
        String string = juser.getText();
        String upper = string.toUpperCase();
        juser.setText(upper);
        this.dispose();
    }//GEN-LAST:event_juserKeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginMenu lm = new LoginMenu();
        lm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void juserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_juserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_juserKeyPressed

    private void jLlaporanmasterdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLlaporanmasterdataMouseClicked
        // TODO add your handling code here:
        CetakBerdasarkan cb = new CetakBerdasarkan();
        jDesktopPane.add(cb);
        if (evt.getClickCount() == 2) {

            String pilihlist = jLlaporanmasterdata.getSelectedValue().toString();

            if(pilihlist.equals("Laporan Daftar Material")){
                
                cb.jBsimpan.setEnabled(true);
                cb.jBsimpan.setText("Cetak Material");
                Dimension parentSize = jDesktopPane.getSize();
                Dimension childSize = cb.getSize();

                //set center screen
                cb.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
                //cb.moveToFront();
                cb.setVisible(true);

            }else if(pilihlist.equals("Laporan Daftar Konsumen")){
                cetakdaftarkonsumen();

            }else if(pilihlist.equals("Laporan Daftar Supplier")){
                cetakdaftarsupplier();
            }
        }
    }//GEN-LAST:event_jLlaporanmasterdataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBitemkeluar;
    public javax.swing.JButton jBitemmasuk;
    public javax.swing.JButton jBkonsumen;
    public javax.swing.JButton jBmasteritem;
    public javax.swing.JButton jBmastersupplier;
    public javax.swing.JButton jBmasteruser;
    public javax.swing.JButton jBpesananpembelian;
    public javax.swing.JButton jBpesananpenjualan;
    public javax.swing.JButton jBreturpembelian;
    public javax.swing.JButton jBreturpenjualan;
    public javax.swing.JButton jBtransaksipembelian;
    public javax.swing.JButton jBtransaksipenjualan;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JInternalFrame jIMenuUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jLlaplainlain;
    public javax.swing.JList jLlaporanmasterdata;
    private javax.swing.JList jLlaptransaksibeli;
    private javax.swing.JList jLlaptransaksijual;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField juser;
    // End of variables declaration//GEN-END:variables
}